name: Workflow Dispatch Proxy

on:
  workflow_dispatch:
    inputs:
      ref:
        description: "Branch or tag to operate on"
        required: true
        default: "main"
      caller:
        description: "Triggered by"
        required: false
        default: "manual or Bitrise"

permissions:
  contents: read  # needed for checkout

jobs:
  test:
    runs-on: macos-latest
    env:
      TARGET_REF: ${{ inputs.ref }}
      CALLER: ${{ inputs.caller }}
    steps:
      - name: Validate ref (basic)
        shell: bash
        run: |
          set -euo pipefail
          # allow alnum, dot, slash, dash, underscore
          if [[ ! "${TARGET_REF}" =~ ^[A-Za-z0-9._/-]+$ ]]; then
            echo "Invalid ref: ${TARGET_REF}" >&2
            exit 1
          fi

      - name: Checkout requested ref
        uses: actions/checkout@v4
        with:
          ref: ${{ env.TARGET_REF }}

      - name: Show who triggered me
        shell: bash
        run: |
          set -euo pipefail
          echo "Event: workflow_dispatch"
          echo "Triggered by \"${CALLER:-unknown}\""
          echo "Checked out ref \"${TARGET_REF}\""